### ISSUE TITLE
Find one internship student for developer

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/HumanResources#213]
we are going to make one system for sales so we need one people

only Javascript needed
100EUR per month 

I want to see CV first then check skill

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko These candidates no.93 Ljubomir Bojadziev and no.104 Goran Nedelkovski have applied earlier this year for interns in our company. We didn't hire them due to closing the internship hiring process at that moment. Can you please look at their cv, if they are suitable to contact them again if they are interested before I post a job advertisement for interns. Thanks.

https://drive.google.com/file/d/1CCB30CWKKbOw-_K0k6mYZJaMNa3w1VBG/view

https://drive.google.com/file/d/1jXq7jZOaOd0iybMcHRJAbK9Zk9U3WCWj/view

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
plz find another people :)
