### ISSUE TITLE
check the status of LinkedIn company pages and recruit pages

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#79]
What can we do on LinkedIn company page?
How does it cost?
Pros, Cons etc...

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

When you ready to do this task, please let me know. let's talk what I want you to do.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I did a research about using Facebook and Linkedin with costs, pros and cons.
Additionally I will see the benefits from paid linkedin profile and how much will it cost approximately, because Linkedin costs depends from the geographical location of the job position, there is no strict pricelist. 

https://docs.google.com/document/d/1WwXFLAFGsIjsgCtitXngMDWgBcR9hHnP2IswRV4dc6k/edit#heading=h.gjdgxs

**Comment by writerity-t-bojan** [comment]
@writerityyuko I made a research about using Premium Linkedin Profile (Recruiter Lite)

https://docs.google.com/spreadsheets/d/1mZCD_LLPExD_YrDLvNFp29SJaI-kd-PbzeBVl1Hx94I/edit#gid=0
